# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://e7liu.github.io/cryptocurrency_sec
title: Cryptocurrency Security
subtitle:  A collection of (mostly) computer security research papers on cryptocurrency.
encoding: "utf-8"

# When this page was last updated
last_updated: Aug 2022

# 可选组件配置
components:
    # 分享
    # weibo,qq,wechat,douban,qzone,linkedin,facebook,twitter
    share:
        enabled: false
        hide-platforms: qq,facebook
    # 不蒜子访问统计
    busuanzi:
        enabled: false
        start_date: 2020-05-03
    # My Popular Repositories
    side_bar_repo:
        enabled: false
    
    # 文章字数统计
    word_count:
        enabled: false
    # 页面右上角，以及「关于」页面的二维码
    # 修改图片请替换 assets/images/qrcode.jpg
    qrcode:
        enabled: false
        image_alt: 闷骚的程序员
    # 维基索引页使用哪种视图，支持 列表（list）/分类（cate）
    wiki:
        view: cate


# 压缩页面内容
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
# 代码高亮风格，支持的 theme 列表见 https://github.com/mzlogin/rouge-themes
highlight_theme: github


# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: Home

  -
    href: /bytopic/
    label: "By Topic"

  -
    href: /byyear/
    label: "By Year"

  -
    href: /byvenue/
    label: "By Venue"

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#      Google      #
# ---------------- #
google:
    analytics_id: UA-80669434-1
    adsense:
        footer: true
        sidebar: true 
        sidebar-detail: true 
        content_header: false
        content_footer: false
